
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.hostname = "controle"

  config.vm.network "private_network", ip: "192.168.1.2"

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision "shell", path: "provisao.sh"

end
